* Aubit4GL Docker

Open Source 4gl compiler

Ref: https://www.aubit.com
Credit: Mike Aubury (Aubit4GL maintainer)

** Test

: docker run --name="aubit4gl" --rm -it map7/aubit4gl /bin/bash
: cd tools/test
: 4glpc hello.4gl -o hello
: fcompile form
: ./hello

** Setup compose

This compose yaml file will help get the compiler to work with PostgreSQL so you can compile your 4GL files which link to your database.

1. Copy the sample
   : cp docker-compose.yml.sample docker-compose.yml

2. Change the areas marked

3. Build
   : docker-compose up -d --build

4. Test
   : docker-compose exec docker-aubit4gl bash

   Change to your 4gl code and compile, then run.

5. Stop
   : docker-compose stop


** Build and updating docker

: docker build -t map7/aubit4gl .;docker push map7/aubit4gl:latest


** todo items
   :PROPERTIES:
   :CREATED:  [2024-06-18 Tue 13:07]
   :END:

- [ ] Upgrade Debian

  - [ ] Debian 11 bullseye

    1. Compiling using 'fl' doesn't work as it truncates the line, test with pappo00a
       This is to do with the gcc version truncating the line.

  - [ ] Debian 12 bookworm

    There is an issue when compiling a 4gl file with Postgresql v15
    client connecting to a Postgresql v9 host.

- [ ] Put option in to use the latest aubit from SVN repo
  https://sourceforge.net/p/aubit4gl/aubit4gl_code/HEAD/tree/aubit4glsrc/trunk/
